fix !unix builds
Geal/rust-syslog pull request #90
Opened 2024-08-05 09:22 UTC by babnskidata

Fix "failed to resolve: use of undeclared type `ErrorKind`" error.

2024-08-20 00:12 UTC, jszwedko commented
We just ran into this on Vector too: https://github.com/vectordotdev/vector/pull/20955

The errors:

```
error[E0433]: failed to resolve: use of undeclared type `ErrorKind`
   --> C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\syslog-7.0.0\src/lib.rs:264:9
    |
264 |     Err(ErrorKind::UnsupportedPlatform)?
    |         ^^^^^^^^^ use of undeclared type `ErrorKind`
    |
help: consider importing this enum
    |
57  + use io::ErrorKind;
    |

error[E0433]: failed to resolve: use of undeclared type `ErrorKind`
   --> C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\syslog-7.0.0\src/lib.rs:275:9
    |
275 |     Err(ErrorKind::UnsupportedPlatform)?
    |         ^^^^^^^^^ use of undeclared type `ErrorKind`
    |
help: consider importing this enum
    |
57  + use io::ErrorKind;
    |

error[E0433]: failed to resolve: use of undeclared type `ErrorKind`
   --> C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\syslog-7.0.0\src/lib.rs:390:9
    |
390 |     Err(ErrorKind::UnsupportedPlatform)?
    |         ^^^^^^^^^ use of undeclared type `ErrorKind`
    |
help: consider importing this enum
    |
57  + use io::ErrorKind;
    |

error[E0433]: failed to resolve: use of undeclared type `ErrorKind`
   --> C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba[1500](https://github.com/vectordotdev/vector/actions/runs/10428621847/job/28885012430#step:6:1501)1f\syslog-7.0.0\src/lib.rs:422:9
    |
422 |     Err(ErrorKind::UnsupportedPlatform)?
    |         ^^^^^^^^^ use of undeclared type `ErrorKind`
    |
help: consider importing this enum
    |
57  + use io::ErrorKind;
```

2024-11-17 05:46 UTC, tisonkun commented
FWIW I made a syslog library https://github.com/fast/fasyslog/ that implement similar functionality and guard the builds with CI.

2024-11-21 21:47 UTC, jszwedko commented
Small bump on this @Geal . Do you think we could merge it to unblock upgrading to the latest version?

2025-03-17 15:37 UTC, sosthene-nitrokey requested changes
This PR does not actually fix compilation for me. There is no `UnsupportedPlatform` variant in [`std::io::ErrorKind`](https://doc.rust-lang.org/std/io/enum.ErrorKind.html)

2025-03-17 15:49 UTC, sosthene-nitrokey commented
It's still not fixed, you need a full error not just the error kind. I made https://github.com/Geal/rust-syslog/pull/94 to fix it.

2025-03-17 17:00 UTC, benjamin-bara-skidata commented
thanks - sorry for that; currently no Win machine available. I'll close this MR :+1:

2025-03-17 17:00 UTC, closed without merging

2025-03-18 08:03 UTC, sosthene-nitrokey commented
You can just check with `cargo check --  --target x86_64-pc-windows-gnu` (using rustup to install the target).